= FirmaEC: firmadigital-api

image:https://github.com/alexjcm/firmadigital-api/actions/workflows/main.yml/badge.svg["Build and testing", link="https://github.com/alexjcm/firmadigital-api/actions/workflows/main.yml"]
image:https://img.shields.io/badge/License-AGPL%20v3-blue.svg[License: AGPL v3, link=https://www.gnu.org/licenses/agpl-3.0] 

Este proyecto implementa los servicios web REST (firmadigital-servicio) para la aplicación de FirmaEC.

== Introducción

Los siguientes pasos le permitirán obtener una copia del proyecto para correrla en la máquina local para propósitos de desarrollo y pruebas.

=== Pre-requisitos

- JDK 17.- Para compilar y ejecutar la aplicación.

- WildFly 35.- Para desplegar la aplicación se necesita un servidor de aplicaciones
disponible en http://www.wildfly.org[wildfly.org]

- Maven 3.- Para compilar y empaquetar se utiliza http://maven.apache.org[Apache Maven].

== Instalación

Para compilar:

----
mvn clean package
----

== Configuración de variables globales

Se establece el subdominio donde se publica el proyecto _firmadigital-servicio_, se deben configurar las variables globales desde el servidor de aplicación:

[source, bash]
----
        <property name="firmadigital-servicio.url" value="https://impws.firmadigital.gob.ec/servicio"/>
----

Se utiliza localhost si el servicio web rest se encuentra en el mismo servidor donde
esta desplegado la api rest. Si estan en servidores diferentes se deberá utilizar la url pública
correspondiente.
firmadigital-servicio.url="http://localhost:7776/servicio"


== Cómo desplegar

Se debe copiar el archivo `target/api.war` a la carpeta `standalone/deploy` de un servidor de aplicaciones WildFly

== Documentación

https://alexjcm.github.io/firmadigital-api[Ver documentación]

== Licencia

Este proyecto está licenciado bajo la licencia AGPL v3.
Revise el archivo link:LICENSE[LICENSE] para más detalles.
