= Firma Digital: API

image:https://github.com/alexjcm/firmadigital-api/actions/workflows/main.yml/badge.svg["Build and testing", link="https://github.com/alexjcm/firmadigital-api/actions/workflows/main.yml"]
image:https://img.shields.io/badge/License-AGPL%20v3-blue.svg[License: AGPL v3, link=https://www.gnu.org/licenses/agpl-3.0] 

_Firma Digital API_ es un proyecto que implementa los servicios web REST para la aplicación FirmaEC.

== Introducción

Los siguientes pasos le permitirán obtener una copia del proyecto para correrla en la máquina local para propósitos de desarrollo y pruebas.

=== Pre-requisitos

- Java Development Kit (JDK) 11.- Para compilar y ejecutar la aplicación.

- WildFly Application Server 29.- Para desplegar la aplicación se necesita un servidor de aplicaciones *Java EE 7* disponible en http://www.wildfly.org[wildfly.org]

- Maven 3.- Para compilar y empaquetar se utiliza http://maven.apache.org[Apache Maven].

== Instalación

Para compilar:

----
mvn clean package
----

== Cómo desplegar

Se debe copiar el archivo `target/api.war` a la carpeta `standalone/deploy` de un servidor de aplicaciones WildFly 29

== Documentación

https://alexjcm.github.io/firmadigital-api[Ver documentación]

== Licencia

Este proyecto está licenciado bajo la licencia AGPL v3.
Revise el archivo link:LICENSE[LICENSE] para más detalles.
